# Generated by Django 4.1.7 on 2023-03-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_units',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
