# Generated by Django 4.1.7 on 2023-04-03 03:08

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_quantity_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemedia',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=recipes.models.generate_image_file_path),
        ),
        migrations.AlterField(
            model_name='recipestepmedia',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=recipes.models.generate_image_file_path),
        ),
    ]
