# Generated by Django 4.1.7 on 2023-04-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipemedia_image_alter_recipestepmedia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_units',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
